### ISSUE TITLE
VLMCSD failed to start

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/windowsserver-mgmttools#18]
**Describe the bug**
VLMCSD failed to start after loading the vlmcsd.kmd

**To Reproduce**
1. Create a vlmcsd.kmd includes Visual Studio, SCCM and SQL Server
2. Load them into the vlmcsd.ini
3. Boom! vlmcsd service failed to start

**Desktop (please complete the following information):**
 - OS: Windows Server 2022 (21H2)

**Comment by TheFlightSimsOfficial** [comment]
vlmcsd.kmd must NOT include Visual Studio, SCCM and SQL Server product keys because these are NOT KMS keys and cannot be activated as KMS protocols, and causes vlmcsd service crash to desktop (CTD).

See [here](https://github.com/TheFlightSims/windowsserver-mgmttools/wiki/VLMCSD---License-Manager#build--manage-database) for more information.
